import { Logger } from '@nestjs/common';
import { chromium, type Browser } from 'playwright-core';
import type { LayoutNode, LayoutSnapshot } from './layout-detect';

/**
 * Execute an uploaded HTML mock-up in a locked-down headless browser and return
 * the DOM it produced.
 *
 * WHY THIS EXISTS — mock-ups generated by an LLM routinely build their entire
 * form at runtime from a config array, leaving markup like:
 *
 *   <table><thead><tr><th>Parameter</th></tr></thead><tbody id="body"></tbody></table>
 *
 * Nothing in that markup is convertible. Rendering the page turns those config
 * arrays back into real `<input>`/`<select>` elements, which the normal
 * extraction path can then read.
 *
 * SECURITY MODEL — the uploaded file is still untrusted. Rendering it is NOT
 * trusting it:
 *
 * - **Isolation is the browser's, not ours.** Chromium's own OS-level sandbox
 *   contains the page; we never evaluate uploaded script in the API process.
 *   (Contrast jsdom, which would run it inside Node with far weaker isolation.)
 * - **No network, at all.** Every request is aborted by a catch-all route, and
 *   the content is injected with `setContent` rather than navigated to — there
 *   is no URL for the page to be loaded from, so no SSRF and no `file://` read
 *   surface even before the route guard.
 * - **No filesystem, no downloads, no extra windows.** Downloads are refused
 *   and pop-ups are closed unread.
 * - **Bounded.** Hard wall-clock timeout and a single-use browser context that
 *   is always torn down, so a mock-up with an infinite loop costs one timeout
 *   rather than a wedged worker.
 * - **The output is re-sanitised.** The returned DOM goes straight back through
 *   `extractFormHtml`, so every existing rule still applies: scripts stripped,
 *   attribute allow-list enforced, hidden content removed. Rendering widens what
 *   we can *read*; it does not widen what reaches the model.
 *
 * Availability is optional: `renderHtmlToDom` returns null when no browser is
 * installed, and callers fall back to the static markup. Local development and
 * CI therefore need no Chromium.
 */

/**
 * Wall-clock cap for the whole render: browser launch, page load and settle.
 *
 * A warm launch renders a form mock-up in ~2s, but a COLD launch on a shared or
 * contended CPU is far slower, and the budget has to cover launch as well as the
 * page. 10s was too tight for that and produced a rejection that read like a
 * problem with the uploaded file.
 */
const RENDER_TIMEOUT_MS = 30_000;

/** Give load-time scripts a moment to finish building the DOM after `load`. */
const SETTLE_MS = 250;

/**
 * Where to find Chromium. Playwright's bundled build does not support Alpine,
 * so the API image installs the distro package and points here.
 */
function executablePath(): string | undefined {
  return process.env.CHROMIUM_PATH || undefined;
}

/** Set `HTML_RENDER_DISABLED=1` to force the static-markup-only path. */
export function isHtmlRenderEnabled(): boolean {
  return process.env.HTML_RENDER_DISABLED !== '1';
}

/**
 * Why a render did or did not happen.
 *
 * The caller needs this to tell an author something true. "No browser installed
 * in this deployment" and "the page ran and genuinely built nothing" look
 * identical from the outside but call for completely different advice — the
 * first is an operator's problem, the second is the author's.
 */
export type HtmlRenderOutcome =
  | {
      status: 'rendered';
      html: string;
      /**
       * Where every label, control and button ended up on screen. Lets
       * layout-detect.ts recover repeating structure from layouts that use no
       * `<table>` at all. Absent if the capture itself failed — the HTML is
       * still usable, so a capture failure must never fail the render.
       */
      layout?: LayoutSnapshot;
    }
  /** HTML_RENDER_DISABLED=1. */
  | { status: 'disabled' }
  /** No usable browser — not installed, or CHROMIUM_PATH points nowhere. */
  | { status: 'unavailable'; detail: string }
  /** A browser launched but the page did not survive it (timeout, crash). */
  | { status: 'failed'; detail: string };

const logger = new Logger('HtmlRender');

/** Launch failures are an operator concern, so say it once rather than never. */
let warnedUnavailable = false;

/**
 * Read back where everything landed on the rendered page.
 *
 * Deliberately dumb: it reports positions and nothing else. All interpretation
 * — clustering into rows and columns, deciding whether a shape is a log or a
 * matrix — happens in layout-detect.ts, outside the browser, where it can be
 * unit-tested without Chromium.
 *
 * Never throws: a snapshot is a bonus on top of the HTML, so a failure here
 * degrades to markup-only detection rather than losing the render.
 */
async function captureLayout(page: {
  evaluate: {
    <T>(fn: () => T): Promise<T>;
    (source: string): Promise<unknown>;
  };
}): Promise<LayoutSnapshot | undefined> {
  try {
    // Playwright ships the callback below to the page as source text. Bundlers
    // that keep function names (esbuild, and therefore tsx/vitest) rewrite named
    // inner functions as `__name(fn, 'fn')`, and that helper does not exist in
    // the page — the callback dies with "__name is not defined". `tsc` emits no
    // such helper, so this only bites under esbuild-based tooling, which is
    // exactly where the tests run. A no-op shim costs nothing and keeps the
    // capture code below type-checked instead of stringly-typed.
    await page.evaluate('globalThis.__name = globalThis.__name || function (f) { return f; }');

    const nodes = await page.evaluate((): LayoutNode[] => {
      const MAX_LABEL_LEN = 160;
      const out: LayoutNode[] = [];

      /** Text belonging to this element itself, not to its descendants. */
      const ownText = (el: Element): string =>
        Array.from(el.childNodes)
          .filter((n) => n.nodeType === 3)
          .map((n) => n.textContent ?? '')
          .join('')
          .replace(/\s+/g, ' ')
          .trim();

      const push = (el: Element, kind: LayoutNode['kind'], text: string) => {
        const r = el.getBoundingClientRect();
        if (r.width === 0 && r.height === 0) return;
        out.push({
          kind,
          text,
          x: Math.round(r.left + window.scrollX),
          y: Math.round(r.top + window.scrollY),
          width: Math.round(r.width),
          height: Math.round(r.height),
        });
      };

      for (const el of Array.from(document.querySelectorAll('*'))) {
        const tag = el.tagName.toLowerCase();

        if (tag === 'input' || tag === 'select' || tag === 'textarea') {
          const type = (el as HTMLInputElement).type?.toLowerCase();
          // Checkboxes and radios are controls, but so are their labels; both
          // are useful, so no special casing beyond hidden inputs.
          if (type !== 'hidden') push(el, 'control', '');
          continue;
        }

        if (tag === 'button' || el.getAttribute('role') === 'button') {
          const text = (el.textContent ?? '').replace(/\s+/g, ' ').trim();
          if (text) push(el, 'button', text);
          continue;
        }

        // Static text. Using OWN text (not textContent) means an ancestor does
        // not duplicate its descendants' labels, while a heading cell that
        // contains both text and a button — "Cannula 1 [+ Day]" — still
        // registers its own "Cannula 1".
        const text = ownText(el);
        if (text && text.length <= MAX_LABEL_LEN) push(el, 'label', text);
      }

      return out;
    });

    return nodes.length ? { nodes } : undefined;
  } catch (err) {
    // Say why, or a silently missing snapshot looks like "this layout has no
    // structure" rather than "the capture broke".
    logger.debug(
      `Layout capture failed, falling back to markup-only detection: ${
        err instanceof Error ? err.message.split('\n')[0] : String(err)
      }`,
    );
    return undefined;
  }
}

/**
 * Render `html` and return `document.documentElement.outerHTML`.
 *
 * Returns null when rendering is disabled or no browser is available — callers
 * must treat that as "use the static markup", never as an error.
 */
export async function renderHtmlToDom(html: string): Promise<string | null> {
  const outcome = await renderHtmlToDomWithOutcome(html);
  return outcome.status === 'rendered' ? outcome.html : null;
}

/**
 * As `renderHtmlToDom`, but reports why nothing came back.
 */
export async function renderHtmlToDomWithOutcome(html: string): Promise<HtmlRenderOutcome> {
  if (!isHtmlRenderEnabled()) return { status: 'disabled' };

  let browser: Browser | undefined;
  let launched = false;
  try {
    browser = await chromium.launch({
      executablePath: executablePath(),
      // Chromium's sandbox is the isolation boundary and stays ON. If a
      // deployment cannot grant the kernel capabilities it needs, disable
      // rendering with HTML_RENDER_DISABLED rather than passing --no-sandbox.
      args: ['--disable-dev-shm-usage', '--disable-gpu'],
      timeout: RENDER_TIMEOUT_MS,
    });
    launched = true;

    const context = await browser.newContext({
      javaScriptEnabled: true,
      acceptDownloads: false,
      offline: true,
    });
    context.setDefaultTimeout(RENDER_TIMEOUT_MS);

    // Belt and braces with `offline`: abort every request outright, so nothing
    // is even attempted — no DNS, no metadata endpoints, no local files.
    await context.route('**/*', (route) => route.abort());
    context.on('page', (p) => {
      // A mock-up that opens a window gets it closed unread.
      if (context.pages().length > 1) void p.close();
    });

    const page = await context.newPage();
    // setContent, never goto: the page has no origin to fetch from.
    await page.setContent(html, { waitUntil: 'load', timeout: RENDER_TIMEOUT_MS });
    await page.waitForTimeout(SETTLE_MS);

    const rendered = await page.evaluate(() => document.documentElement.outerHTML);
    const layout = await captureLayout(page);
    await context.close();
    if (typeof rendered !== 'string' || rendered.length === 0) {
      return { status: 'failed', detail: 'the page produced no DOM' };
    }
    return { status: 'rendered', html: rendered, layout };
  } catch (err) {
    const detail = err instanceof Error ? err.message.split('\n')[0] : String(err);
    if (!launched) {
      // No browser to launch. Silent fallback here is what made a missing
      // Chromium indistinguishable from an empty mock-up, so say it once.
      if (!warnedUnavailable) {
        warnedUnavailable = true;
        logger.warn(
          `Headless browser unavailable, so HTML mock-ups that build their form at runtime cannot be converted: ${detail}. ` +
            'Install Chromium in the API image, or point CHROMIUM_PATH at a local browser. ' +
            'Set HTML_RENDER_DISABLED=1 to silence this.',
        );
      }
      return { status: 'unavailable', detail };
    }
    return { status: 'failed', detail };
  } finally {
    await browser?.close().catch(() => undefined);
  }
}
