import { chromium, type Browser } from 'playwright-core';

/**
 * Execute an uploaded HTML mock-up in a locked-down headless browser and return
 * the DOM it produced.
 *
 * WHY THIS EXISTS — mock-ups generated by an LLM routinely build their entire
 * form at runtime from a config array, leaving markup like:
 *
 *   <table><thead><tr><th>Parameter</th></tr></thead><tbody id="body"></tbody></table>
 *
 * Nothing in that markup is convertible. Rendering the page turns those config
 * arrays back into real `<input>`/`<select>` elements, which the normal
 * extraction path can then read.
 *
 * SECURITY MODEL — the uploaded file is still untrusted. Rendering it is NOT
 * trusting it:
 *
 * - **Isolation is the browser's, not ours.** Chromium's own OS-level sandbox
 *   contains the page; we never evaluate uploaded script in the API process.
 *   (Contrast jsdom, which would run it inside Node with far weaker isolation.)
 * - **No network, at all.** Every request is aborted by a catch-all route, and
 *   the content is injected with `setContent` rather than navigated to — there
 *   is no URL for the page to be loaded from, so no SSRF and no `file://` read
 *   surface even before the route guard.
 * - **No filesystem, no downloads, no extra windows.** Downloads are refused
 *   and pop-ups are closed unread.
 * - **Bounded.** Hard wall-clock timeout and a single-use browser context that
 *   is always torn down, so a mock-up with an infinite loop costs one timeout
 *   rather than a wedged worker.
 * - **The output is re-sanitised.** The returned DOM goes straight back through
 *   `extractFormHtml`, so every existing rule still applies: scripts stripped,
 *   attribute allow-list enforced, hidden content removed. Rendering widens what
 *   we can *read*; it does not widen what reaches the model.
 *
 * Availability is optional: `renderHtmlToDom` returns null when no browser is
 * installed, and callers fall back to the static markup. Local development and
 * CI therefore need no Chromium.
 */

/** Wall-clock cap for the whole render. A form mock-up needs a fraction of this. */
const RENDER_TIMEOUT_MS = 10_000;

/** Give load-time scripts a moment to finish building the DOM after `load`. */
const SETTLE_MS = 250;

/**
 * Where to find Chromium. Playwright's bundled build does not support Alpine,
 * so the API image installs the distro package and points here.
 */
function executablePath(): string | undefined {
  return process.env.CHROMIUM_PATH || undefined;
}

/** Set `HTML_RENDER_DISABLED=1` to force the static-markup-only path. */
export function isHtmlRenderEnabled(): boolean {
  return process.env.HTML_RENDER_DISABLED !== '1';
}

/**
 * Render `html` and return `document.documentElement.outerHTML`.
 *
 * Returns null when rendering is disabled or no browser is available — callers
 * must treat that as "use the static markup", never as an error.
 */
export async function renderHtmlToDom(html: string): Promise<string | null> {
  if (!isHtmlRenderEnabled()) return null;

  let browser: Browser | undefined;
  try {
    browser = await chromium.launch({
      executablePath: executablePath(),
      // Chromium's sandbox is the isolation boundary and stays ON. If a
      // deployment cannot grant the kernel capabilities it needs, disable
      // rendering with HTML_RENDER_DISABLED rather than passing --no-sandbox.
      args: ['--disable-dev-shm-usage', '--disable-gpu'],
      timeout: RENDER_TIMEOUT_MS,
    });

    const context = await browser.newContext({
      javaScriptEnabled: true,
      acceptDownloads: false,
      offline: true,
    });
    context.setDefaultTimeout(RENDER_TIMEOUT_MS);

    // Belt and braces with `offline`: abort every request outright, so nothing
    // is even attempted — no DNS, no metadata endpoints, no local files.
    await context.route('**/*', (route) => route.abort());
    context.on('page', (p) => {
      // A mock-up that opens a window gets it closed unread.
      if (context.pages().length > 1) void p.close();
    });

    const page = await context.newPage();
    // setContent, never goto: the page has no origin to fetch from.
    await page.setContent(html, { waitUntil: 'load', timeout: RENDER_TIMEOUT_MS });
    await page.waitForTimeout(SETTLE_MS);

    const rendered = await page.evaluate(() => document.documentElement.outerHTML);
    await context.close();
    return typeof rendered === 'string' && rendered.length > 0 ? rendered : null;
  } catch {
    // Missing browser, launch failure, timeout, runaway script — all mean the
    // same thing to the caller: no rendered DOM, carry on with the markup.
    return null;
  } finally {
    await browser?.close().catch(() => undefined);
  }
}
